### ISSUE TITLE
IoT User stories

### ISSUE THREAD

**Issue by lucas-maia-morais** [lucas-maia-morais/gsl-iot-22-motomamis#2]
Use this structure to write the user stories:

“As a [persona], I [want to], [so that].”

Persona = The persona for the user
Wants to = What's is trying to achieve
So that = why the user need this

Example: As Max, I want to invite my friends, so we can enjoy this service together.
Example2: As a user, I want to use a search field to type a city, name, or street, so that I could find matching hotel options.

Follow this [link](https://www.atlassian.com/agile/project-management/user-stories) for more 
details.

**Comment by lucas-maia-morais** [comment]
- [ ] [Solution Description Page](https://github.com/kabartsjc/gsl-iot-2022/blob/main/SOLUTION_DESCRIPTION.md)
- [ ] [Client Stage - Android Device](https://github.com/kabartsjc/gsl-iot-2022/blob/main/templates/android/ANDROID.md)
- [ ] [Gateway / Edge Stage - Mosquitto Broker](https://github.com/kabartsjc/gsl-iot-2022/blob/main/templates/mosquitto/MOSQUITTO.md)
- [ ] [Cloud Stage - Python MYSQL x Mosquitto Broker Integration](https://github.com/kabartsjc/gsl-iot-2022/blob/main/templates/cloud/MYSQL.md)
- [ ] [Cloud Stage - Dashboard](https://github.com/kabartsjc/gsl-iot-2022/blob/main/templates/cloud/DASHBOARD.md)

**Comment by DANIEL-NAVA-M** [comment]
As a victim of a natural disaster, I want to send an alert and notify about my status and my position to the center, hoping to receive help and support as soon as possible.

**Comment by Ly1515** [comment]
As a victim

**Comment by OliviaNavarreteC** [comment]
User Story: As an ingenieer, I want to optimize a better sewage system so that when it occurs a flooding, the population don't have to lose their houses
Persona= Ingenieer 
Wants to: Optimeze a better sewage system 
So that: When it occurs a flooding, the population don't have to lose their houses

**Comment by OliviaNavarreteC** [comment]
User Story:As a victim, I want a way to keep in touch with family so that if I got injured they can know about my health condition
Persona= Victim 
Wants to=  I want a way to keep in touch with family
So that= If I got injured they can know about my health condition

**Comment by OliviaNavarreteC** [comment]
User Story: As an ingenieer, I want to optimize a better sewage system so that when it occurs a flooding, the population don't have to lose their houses
Persona= Ingenieer 
Wants to=Optimeze a better sewage system 
So that= When it occurs a flooding, the population don't have to lose their houses

**Comment by OliviaNavarreteC** [comment]
User Story:As a user of the service, I want a way to keep in touch with family so that if I got injured they can know about my health condition
Persona= Victim
Wants to= I want a way to keep in touch with family
So that= If I got injured they can know about my health condition

**Comment by OliviaNavarreteC** [comment]
User Story: As an engineer, I want to map out the zones of less risk of flooding, so that the government can site refuges there
Persona= Ingenieer 
Wants to: Map out the zones of  less risk of flooding
So that: The government can site refuges there

**Comment by OliviaNavarreteC** [comment]
User story: As a user or the service, I want a device that can monitor me when if I am in the risk zone, so that I can be protected by the emergency services
Persona=User
Wants to= A device can monitor me 
So that= I can be protected

**Comment by OliviaNavarreteC** [comment]
User Story: As a victim of a natural disaster, I want to send a message to my emergency contact and also to the emergency services, so that they can assistant me as soon as possible
Persona= Victim
Wants to= Send a message to my emergency contact and also to the emergency services
So that= They can assistant me as soon as possible

**Comment by OliviaNavarreteC** [comment]
User Story: As an engineer, I want to map out the zones of less risk of flooding, so that the government can site refuges there
Persona= Engenieer 
Wants to=Map out the zones of less risk of flooding
So that = The government can site refuges there
