### ISSUE TITLE
Network Features requirements and acceptance criteria

### ISSUE THREAD

**Issue by lucas-maia-morais** [lucas-maia-morais/gsl-iot-22-motomamis#5]
We're going to write the acceptance criteria as follows:

- User Story: [What you prepared]
    - Acceptance Criteria
        - [Objective Criteria]

What you prepared = means what you have written previously
Objective Criteria = Think about something you could test at the end

Example
- User story: As a user, I want to use a search field to type a city, name, or street, so that I could find matching hotel options.
    - Acceptance criteria
        - The search field is placed on the top bar
        - The field contains a placeholder with a grey-colored text: “Where are you going?”
        - ...

Example 2
- User Story: As a user, I want to authenticate myself in a secure way, to listen to music
    - Acceptance Criteria
        - Secure means that the password will be encrypted with SHA256 before requesting in the backend
        - In the backend it will be encrypted another time with SHA26 before looking in the database

For more information check this [link](https://www.altexsoft.com/blog/business/acceptance-criteria-purposes-formats-and-best-practices/)

**Comment by lucas-maia-morais** [comment]
- [x] [Infrastructure - Mininet-Wifi](https://github.com/kabartsjc/gsl-iot-2022/blob/main/templates/mininet/MININET.md)

**Comment by ArturAssisComp** [comment]
The acceptance criteria were added in the branch created for the issue #4 .
